export const users = [
    { name: "Alice", age: 25, id: 1, location: "New York" },
    { name: "Bob", age: 30, id: 2, location: "Los Angeles" },
    { name: "Charlie", age: 35, id: 3, location: "Chicago" },
    { name: "David", age: 40, id: 4, location: "Houston" },
    { name: "Eve", age: 22, id: 5, location: "Phoenix" },
    { name: "Frank", age: 28, id: 6, location: "Philadelphia" },
    { name: "Grace", age: 33, id: 7, location: "San Antonio" },
    { name: "Hannah", age: 29, id: 8, location: "San Diego" },
    { name: "Irene", age: 24, id: 9, location: "Dallas" },
    { name: "Jack", age: 37, id: 10, location: "San Jose" },
    { name: "Kenny", age: 31, id: 11, location: "Austin" },
    { name: "Lilly", age: 26, id: 12, location: "Jacksonville" },
    { name: "Mason", age: 34, id: 13, location: "Fort Worth" },
    { name: "Nina", age: 23, id: 14, location: "Columbus" },
    { name: "Oliver", age: 38, id: 15, location: "Charlotte" },
    { name: "Paul", age: 32, id: 16, location: "San Francisco" },
    { name: "Quincy", age: 27, id: 17, location: "Indianapolis" },
    { name: "Rita", age: 21, id: 18, location: "Seattle" },
    { name: "Sam", age: 36, id: 19, location: "Denver" },
    { name: "Tom", age: 29, id: 20, location: "Washington" },
    { name: "Ursula", age: 25, id: 21, location: "Boston" },
    { name: "Vera", age: 30, id: 22, location: "El Paso" },
    { name: "Walter", age: 33, id: 23, location: "Detroit" },
    { name: "Xander", age: 28, id: 24, location: "Nashville" },
    { name: "Yvonne", age: 31, id: 25, location: "Portland" },
    { name: "Zane", age: 24, id: 26, location: "Memphis" },
    { name: "Amelia", age: 22, id: 27, location: "Oklahoma City" },
    { name: "Blake", age: 34, id: 28, location: "Las Vegas" },
    { name: "Chloe", age: 27, id: 29, location: "Louisville" },
    { name: "Dylan", age: 29, id: 30, location: "Baltimore" },
    { name: "Ella", age: 36, id: 31, location: "Milwaukee" },
    { name: "Felix", age: 30, id: 32, location: "Albuquerque" },
    { name: "Gavin", age: 26, id: 33, location: "Tucson" },
    { name: "Holly", age: 39, id: 34, location: "Fresno" },
    { name: "Ivy", age: 32, id: 35, location: "Sacramento" },
    { name: "Jake", age: 35, id: 36, location: "Kansas City" },
    { name: "Kaitlyn", age: 24, id: 37, location: "Mesa" },
    { name: "Leo", age: 28, id: 38, location: "Atlanta" },
    { name: "Maya", age: 31, id: 39, location: "Omaha" },
    { name: "Nolan", age: 33, id: 40, location: "Raleigh" },
    { name: "Opal", age: 25, id: 41, location: "Long Beach" },
    { name: "Patrick", age: 36, id: 42, location: "Lubbock" },
    { name: "Quinn", age: 29, id: 43, location: "New Orleans" },
    { name: "Riley", age: 31, id: 44, location: "Tampa" },
    { name: "Sophie", age: 24, id: 45, location: "St. Louis" },
    { name: "Tyler", age: 38, id: 46, location: "Cleveland" },
    { name: "Uma", age: 27, id: 47, location: "Chula Vista" },
    { name: "Victor", age: 32, id: 48, location: "Bakersfield" },
    { name: "Will", age: 30, id: 49, location: "Stockton" },
    { name: "Ximena", age: 28, id: 50, location: "Corpus Christi" },
    { name: "Yasmin", age: 25, id: 51, location: "Anchorage" },
    { name: "Zachary", age: 34, id: 52, location: "Henderson" },
    { name: "Ava", age: 22, id: 53, location: "Saint Paul" },
    { name: "Ben", age: 31, id: 54, location: "Surprise" },
    { name: "Carla", age: 27, id: 55, location: "Bridgeport" },
    { name: "Danny", age: 28, id: 56, location: "McKinney" },
    { name: "Emily", age: 35, id: 57, location: "Fullerton" },
    { name: "Freya", age: 24, id: 58, location: "Corona" },
    { name: "Gabe", age: 33, id: 59, location: "Shreveport" },
    { name: "Hank", age: 32, id: 60, location: "McAllen" },
    { name: "Iris", age: 29, id: 61, location: "Lafayette" },
    { name: "James", age: 30, id: 62, location: "Billings" },
    { name: "Kate", age: 27, id: 63, location: "Burlington" },
    { name: "Liam", age: 28, id: 64, location: "Frisco" },
    { name: "Mia", age: 23, id: 65, location: "Pearland" },
    { name: "Nash", age: 34, id: 66, location: "Columbia" },
    { name: "Olivia", age: 32, id: 67, location: "Simi Valley" },
    { name: "Perry", age: 26, id: 68, location: "Waco" },
    { name: "Quincy", age: 37, id: 69, location: "Toledo" },
    { name: "Rose", age: 29, id: 70, location: "Waterbury" },
    { name: "Steve", age: 36, id: 71, location: "Newport News" },
    { name: "Tina", age: 33, id: 72, location: "Vancouver" },
    { name: "Ulysses", age: 30, id: 73, location: "Fargo" },
    { name: "Vanessa", age: 35, id: 74, location: "Green Bay" },
    { name: "Wendy", age: 27, id: 75, location: "Spokane" },
    { name: "Xander", age: 34, id: 76, location: "Draper" },
    { name: "Yara", age: 25, id: 77, location: "Syracuse" },
    { name: "Zane", age: 30, id: 78, location: "Shreveport" },
    { name: "Abby", age: 28, id: 79, location: "Cedar Rapids" },
    { name: "Brad", age: 32, id: 80, location: "Antioch" },
    { name: "Cora", age: 24, id: 81, location: "O'Fallon" },
    { name: "Dustin", age: 33, id: 82, location: "Lakewood" },
    { name: "Eva", age: 27, id: 83, location: "Kennewick" },
    { name: "Finn", age: 36, id: 84, location: "Lansing" },
    { name: "Gina", age: 30, id: 85, location: "Battle Creek" },
    { name: "Holly", age: 25, id: 86, location: "Evansville" },
    { name: "Ivy", age: 28, id: 87, location: "Waterloo" },
    { name: "Jack", age: 33, id: 88, location: "Davenport" },
    { name: "Kara", age: 32, id: 89, location: "Pocatello" },
    { name: "Leo", age: 29, id: 90, location: "Joplin" },
    { name: "Mona", age: 30, id: 91, location: "Parkersburg" },
    { name: "Nina", age: 35, id: 92, location: "Hickory" },
    { name: "Oscar", age: 28, id: 93, location: "Mansfield" },
    { name: "Penny", age: 22, id: 94, location: "Shreveport" },
    { name: "Quincy", age: 31, id: 95, location: "Wilmington" },
    { name: "Riley", age: 27, id: 96, location: "Lima" },
    { name: "Sophia", age: 28, id: 97, location: "Montgomery" },
    { name: "Tim", age: 30, id: 98, location: "Boise" },
    { name: "Ursula", age: 31, id: 99, location: "Auburn" },
    { name: "Vince", age: 32, id: 100, location: "Grand Junction" }
];
